// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.concord.proto;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.concord.protobuf.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.concord.protobuf.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<StudentResponse>
      getStudentResponseList();
  /**
   * <code>repeated .com.concord.protobuf.StudentResponse studentResponse = 1;</code>
   */
  StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .com.concord.protobuf.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .com.concord.protobuf.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends com.concord.proto.StudentResponseOrBuilder>
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .com.concord.protobuf.StudentResponse studentResponse = 1;</code>
   */
  com.concord.proto.StudentResponseOrBuilder getStudentResponseOrBuilder(
          int index);
}
